name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --build-arg RUN_ID=${{ github.run_id }} -t ctrunner .

      - name: Save Docker Image
        run: |
          docker save ctrunner -o ./ctrunner.tar
          ls -lh ./ctrunner.tar

      - name: Upload Docker Image to DigitalOcean
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_IP_ADDR }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "./ctrunner.tar"
          target: "~/ctrunner"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_IP_ADDR }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker load -i ~/ctrunner/ctrunner.tar
            rm ~/ctrunner/ctrunner.tar

            docker rm -f ctrunner_container || true
            docker container prune -f

            cd ~/ctrunner

            mkdir -p db
            touch db/database.db

            docker run -d \
                -p 8083:8080 \
                -v $(pwd)/db:/app/db \
                -v $(pwd)/.env:/app/.env \
                -e APP_VERSION=${{ github.run_id }} \
                --name ctrunner_container ctrunner

            docker system prune -a --volumes -f
